# To clean the Global environment
rm(list=ls()) 

#############################################################
#####                     To read                       #####
#############################################################
# This R script is the second step after merging Scopus and Web of Sciences (BibTex format)
# This script allows a bibliometric analysis on the Keywords 
# The choice of the keywords to analyse (Authors Keywords, Index Keywords, Both) is done in the previous script

#############################################################
#####                 File requirement                  #####
#############################################################
# The files to be imported are generated by the first code Merger_1.R

library(dplyr)
library(stringr)
library(tidyr)
library(hablar)
library(ggplot2)
library(maps)
library(countrycode)
library(RColorBrewer)
library(bibliometrix)
library(tidyverse)
library(plotly)
library(corrplot)
library(reshape2)

#######################################################################
#####                           Function                          #####
#######################################################################

#### Function to search and replace ####

# Include function to duplicate {Marc Schwartz (via MN) on http://r.789695.n4.nabble.com/replace-values-in-data-frame-td803416.html}
gsr <- function(Source, Search, Replace) 
{ 
  if (length(Search) != length(Replace)) 
    stop("Search and Replace Must Have Equal Number of Items\n") 
  
  Changed <- as.character(Source) 
  
  for (i in 1:length(Search)) 
  { 
    cat("Replacing: ", Search[i], " With: ", Replace[i], "\n") 
    Changed <- replace(Changed, Changed == Search[i], Replace[i]) 
  } 
  
  cat("\n") 
  
  Changed 
}

#######################################################################
#####                         Data loading                        #####
#######################################################################

# set working directory

# read the export *.csv document from Merger, separation ",", and place it in data.frame "MergerOriginalData"
MergerOriginalData <- read.csv("Merger_Dataset_Final.txt", sep="\t", header=TRUE)


#######################################################################
#####                            Keywords                         #####
#######################################################################

#Split Column "AIK" in row by the separator ";", remove leading white space to generate list
MergeDataKeywordList <- MergerOriginalData %>% 
  mutate(AIKeywords = strsplit(as.character(AIK), ";")) %>% 
  unnest(AIKeywords) %>%
  mutate_if(is.character, str_trim)

# Upper case "AIK" in "KeywordList" and save in dataframe
# Extract list of "AIK" and remove duplicate
MergeDataKeywordList$AIKeywords <- toupper(MergeDataKeywordList$AIKeywords)
KeywordList <- MergeDataKeywordList %>%
  select(AIKeywords)
Keyword <- KeywordList %>%
  distinct()

# Most cited keywords before correction - Extract a list of keywords to apply corrections
KeywordListCount <- aggregate(KeywordList$AIKeywords, by=list(Freq=KeywordList$AIKeywords), FUN=length)
names(KeywordListCount) <- c("Keywords","Count")
#write.csv(KeywordListCount,"Keywords to correct.csv")

#############################################################
#####                  Data cleansing                   #####
#############################################################

#Correction to the keywords can be applied at this stage. This can be done in Notepad++, Excel etc. The ultimate order of the list must be kept so it can be binded to the orignial data.

#read the corrected list of keywords and combine it to the original list
KeywordsCorrected <- read.csv("Merger_AKeywords_Corrected.txt", sep="\t", header=TRUE)
KeywordsCorrected <- as.data.frame(KeywordsCorrected)
MergeDataKeywordList$KeywordsCorrected <- gsr(as.character(MergeDataKeywordList$AIKeywords),as.character(KeywordsCorrected$Keywords),as.character(KeywordsCorrected$KeywordsCorrected))


#############################################################
#####               Data analysis - Keywords            #####
#############################################################

#####________________Table Keyword Count________________#####
# Count the number of references with DES, DEW, IDS and IDW as well as their % to the total number of references
Totalref <- data.frame(nrow(MergerOriginalData))
CountDES <- data.frame(table(MergerOriginalData$AIKS, exclude = ""));CountDES
CountDEW <- data.frame(table(MergerOriginalData$AIKW, exclude = ""));CountDEW
CountIDS <- data.frame(table(MergerOriginalData$IDS, exclude = ""));CountIDS
CountIDW <- data.frame(table(MergerOriginalData$IDW, exclude = ""));CountIDW

KeywordTable_1 <- data.frame(nrow(CountDES))
KeywordTable_1[2,1] <- nrow(CountDEW)
KeywordTable_1[3,1] <- nrow(CountIDS)
KeywordTable_1[4,1] <- nrow(CountIDW)

rownames(KeywordTable_1)[rownames(KeywordTable_1)=="1"] <- "Author keywords Scopus"
rownames(KeywordTable_1)[rownames(KeywordTable_1)=="2"] <- "Author keywords WoS"
rownames(KeywordTable_1)[rownames(KeywordTable_1)=="3"] <- "Index keywords Scopus"
rownames(KeywordTable_1)[rownames(KeywordTable_1)=="4"] <- "Index keywords WoS"

KeywordTable_1[1,2] <- (KeywordTable_1[1,1]/Totalref)*100
KeywordTable_1[2,2] <- (KeywordTable_1[2,1]/Totalref)*100
KeywordTable_1[3,2] <- (KeywordTable_1[3,1]/Totalref)*100
KeywordTable_1[4,2] <- (KeywordTable_1[4,1]/Totalref)*100

KeywordTable_1 <- rownames_to_column(KeywordTable_1)
names(KeywordTable_1) <- c("Keywords", "Count", "%")

#Export to text file
#write.table(KeywordTable_1, file = "Merger_KeywordTable_1.csv", sep = ",", row.names = F)

#####________________Graph Preparation________________#####
#Count to number of time the same year is repeated in the "ScopusKeywordList$Year" and save in a data.frame "Year" 
PublicationYear<- data.frame(table(MergerOriginalData$PY));PublicationYear
names(PublicationYear) <- c("Year","Publications")

#count the number of keywords per title paper 
MergeDataKeywordListTemp1 <- MergeDataKeywordList  %>%
  select(PY,TI,KeywordsCorrected) %>%
  distinct()
names(MergeDataKeywordListTemp1) <- c("Year","Title","KeywordsCorrected")

MergeDataKeywordListTemp2 <- MergeDataKeywordListTemp1[complete.cases(MergeDataKeywordListTemp1), ]
sum(is.na(MergeDataKeywordListTemp2$KeywordsCorrected))

MergeDataKeywordYearCount <- aggregate(MergeDataKeywordListTemp2$Year, by=list(Year=MergeDataKeywordListTemp2$Year, Rtitle=MergeDataKeywordListTemp2$KeywordsCorrected), FUN=length)
MergeDataKeywordTotalCount <- aggregate(MergeDataKeywordListTemp2$Year, by=list(Rtitle=MergeDataKeywordListTemp2$KeywordsCorrected), FUN=length)
# MergeDataKeywordListTemp5 <- aggregate(MergeDataKeywordListTemp2, by=list(MergeDataKeywordListTemp2$Year), FUN=length)

# narrowing range for plot
MergeDataKeywordNarrowRangeGraph <- subset(MergeDataKeywordTotalCount,x>=5)

SubsetKeywordNarrowRangeGraph <-subset(MergeDataKeywordYearCount,Rtitle %in% MergeDataKeywordNarrowRangeGraph$Rtitle)
#Reduced <- subset(Condensed, SummaryKeywords$weight>0.007)
SubsetKeywordNarrowRangeGraph$x <- as.numeric(SubsetKeywordNarrowRangeGraph$x)

#############################################################
#####                      GRAPH                        #####
#############################################################

#####______________Graph for keywords with a frequency >=5 ______________##########
# Create a new variable from incidence
SubsetKeywordNarrowRangeGraph$Incidenceweight <- cut(SubsetKeywordNarrowRangeGraph$x,
                                                     breaks = c(-1,0,1,2,5,10,max(SubsetKeywordNarrowRangeGraph$x,na.rm=T)),
                                                     labels=c("0","1","2","3-5","6-10","11-20"))

GraphTemp1 <- SubsetKeywordNarrowRangeGraph %>%
  # convert state to factor and reverse order of levels
  mutate(KeywordsCorrected=factor(Rtitle,levels=rev(sort(unique(Rtitle))))) %>%
  # create a new variable from count
  mutate(countfactor=cut(x,breaks=c(-1,0,1,2,5,10,max(x,na.rm=T)),
                         labels=c("0","1","2","3-5","6-10","11-20")))  %>%
  # change level order
  mutate(countfactor=factor(as.character(countfactor),levels=rev(levels(countfactor))))
# KeywordList$WYear <- gsr(KeywordList$Year,year$Var1,1/year$Freq)
GraphTemp2 <- aggregate(GraphTemp1[, 1], list(GraphTemp1$KeywordsCorrected), min)

GraphTemp1$graphorder <- as.numeric(gsr(GraphTemp1$KeywordsCorrected,GraphTemp2$Group.1,GraphTemp2$x))

# assign text colour
textcol <- "black"

# further modified ggplot
p <- ggplot(GraphTemp1,aes(x=Year,y=reorder(KeywordsCorrected,graphorder),fill=countfactor))+
  geom_tile(colour="white",size=0.2)+
  guides(fill=guide_legend(title="Count"))+
  #  labs(x="",y="",title="Keywords found in fibre publication")+
  labs(x="Year",y="",title="")+
  scale_y_discrete(expand=c(0,0))+
  scale_x_continuous(breaks=c(1965,1975,1985,1995,2005,2015))+
  scale_fill_manual(values=c("#08519C","#3182BD","#6BAED6","#9ECAE1","#C6DBEF","#EFF3FF"),na.value = "grey90")+
  #coord_fixed()+
  theme_grey(base_size=14)+
  theme(legend.position="right",legend.direction="vertical",
        legend.title=element_text(colour=textcol),
        legend.margin=margin(grid::unit(0,"cm")),
        legend.text=element_text(colour=textcol,),
        legend.key.height=grid::unit(0.8,"cm"),
        legend.key.width=grid::unit(0.2,"cm"),
        axis.text.x=element_text(size=8,colour=textcol),
        axis.text.y=element_text(vjust=0.2,colour=textcol),
        axis.ticks=element_line(size=0.4),
        plot.background=element_blank(),  # element_rect(fill, colour, size, linetype, color))
        panel.border=element_blank(),
        plot.margin=margin(0.7,0.4,0.1,0.2,"cm"),
        plot.title=element_text(colour=textcol,hjust=0,size=12))
show(p)
ggplotly(p)
#ggsave("ScopWoS_KeywordTrend.png", p, width = 11, height = 10, units = "in", dpi=150, path = "Results", path = "Results")


#####______________Graph for Techniques analysis only______________##########

#Create a new variable of MergeKeywordNarrowRangeGraph to not overwrite data
MergeDataKeywordNarrowRangeGraph2 <-subset(MergeDataKeywordYearCount,Rtitle %in% MergeDataKeywordNarrowRangeGraph$Rtitle)

#Reduced <- subset(Condensed, SummaryKeywords$weight>0.007)
MergeDataKeywordNarrowRangeGraph2$x <- as.numeric(MergeDataKeywordNarrowRangeGraph2$x)

# Create a list of techniques to include
techniques.list <- paste(c("MICROSPECTROPHOTOMETRY (MSP)",
                           "INFRARED SPECTROSCOPY (IR)",
                           "FOURIER-TRANSFORM INFRARED SPECTROSCOPY (FT-IR)",
                           "SPECTROPHOTOMETRY",
                           "MICROSCOPY",
                           "MASS SPECTROMETRY (MS)",
                           "SCANNING ELECTRON MICROSCOPY (SEM)",
                           "PRINCIPAL COMPONENT ANALYSIS (PCA)",
                           "THIN-LAYER CHROMATOGRAPHY (TLC)",
                           "RAMAN",
                           "CAPILLARY ELECTROPHORESIS (CE)",
                           "GAS CHROMATOGRAPHY–MASS SPECTROMETRY (GC–MS)",
                           "HOLLOW-FIBRE LIQUID-PHASE MICROEXTRACTION (HF-LPME)",
                           "POLARIZED LIGHT MICROSCOPY",
                           "SPECTROSCOPY"), collapse = ';')
techniqueslist <- as.data.frame(techniques.list)

#Split Column "techniques.list" in row by the separator ";", remove leading white space to generate list
techniqueslist <- techniqueslist %>% 
  mutate(techniques.list = strsplit(as.character(techniques.list), ";")) %>% 
  unnest(techniques.list) %>%
  mutate_if(is.character, str_trim)

# Select from "MergeDataKeywordNarrowRangeGraph2" every keywords from "techniques.list" and place it in a new list "TechniqueList"
TechniqueList <-subset(MergeDataKeywordNarrowRangeGraph2,Rtitle %in% techniqueslist$techniques.list)

# Rename some of the techniques that are too long
# read the corrected list of techniques and combine it to TechniqueList
TechniqueCorrected <- read.csv("Technique Name Corrected_ScopWoS.txt", sep="\t", header=TRUE)
TechniqueList$Rtitle2 <- gsr(TechniqueList$Rtitle,TechniqueCorrected$name, as.character(TechniqueCorrected$Name.Corrected))
TechniqueList <- TechniqueList %>% select("Year", "Rtitle2", "x")
names(TechniqueList) <- c("Year", "Rtitle", "x")


#### plot second graph
# Create a new variable from incidence
TechniqueList$Incidenceweight <- cut(TechniqueList$x,
                                     breaks = c(-1,0,1,2,max(TechniqueList$x,na.rm=T)),
                                     labels=c("0","1","2","3-5"))

GraphTemp1Bis <- TechniqueList %>%
  # convert state to factor and reverse order of levels
  mutate(KeywordsCorrected=factor(Rtitle,levels=rev(sort(unique(Rtitle))))) %>%
  # create a new variable from count
  mutate(countfactor=cut(x,breaks=c(-1,0,1,2,max(x,na.rm=T)),
                         labels=c("0","1","2","3-5")))  %>%
  # change level order
  mutate(countfactor=factor(as.character(countfactor),levels=rev(levels(countfactor))))
# InterpolKeywordList$WYear <- gsr(InterpolKeywordList$Year,year$Var1,1/year$Freq)
GraphTemp2 <- aggregate(GraphTemp1Bis[, 1], list(GraphTemp1Bis$KeywordsCorrected), min)

GraphTemp1Bis$graphorder <- as.numeric(gsr(GraphTemp1Bis$KeywordsCorrected,GraphTemp2$Group.1,GraphTemp2$x))
GraphTemp1Bis
# assign text colour
textcol <- "black"


# further modified ggplot
p1 <- ggplot(GraphTemp1Bis,aes(x=Year,y=reorder(KeywordsCorrected,graphorder),fill=countfactor))+
  geom_tile(colour="white",size=0.2)+
  guides(fill=guide_legend(title="Count"))+
  #  labs(x="",y="",title="Keywords found in gunshot residue publication")+
  labs(x="Year",y="",title="")+
  scale_y_discrete(expand=c(0,0),labels = function(x) str_wrap(x, width = 30))+
  scale_x_continuous(breaks=c(1965,1975,1985,1995,2005,2015))+
  scale_fill_manual(values=c("#f46d43","#fdae61","#fee08b","#d5ee52","#77c86c","#66afc6","#ddf1da"),na.value = "grey90")+
  coord_fixed()+
  theme_grey(base_size=8)+
  theme(legend.position="right",legend.direction="vertical",
        legend.title=element_text(colour=textcol),
        legend.margin=margin(grid::unit(0,"cm")),
        legend.text=element_text(colour=textcol,size=7),
        legend.key.height=grid::unit(0.8,"cm"),
        legend.key.width=grid::unit(0.2,"cm"),
        axis.text.x=element_text(size=8,colour=textcol),
        axis.text.y=element_text(vjust=0.2,colour=textcol),
        axis.ticks=element_line(size=0.4),
        plot.background=element_blank(),  # element_rect(fill, colour, size, linetype, color))
        panel.border=element_blank(),
        plot.margin=margin(0.7,0.4,0.1,0.2,"cm"),
        plot.title=element_text(colour=textcol,hjust=0,size=12))
show(p1)
ggplotly(p1)
ggsave("ScopWoS_Techniques Keyword Trend.png", p1,  width = 8, height = 3, units = "in", dpi=150, path = "Results")

#####______________Graph for Textile analysis only______________##########

#Create a new variable of ScopusKeywordNarrowRangeGraph to not overwrite data
MergeDataKeywordNarrowRangeGraph3 <-subset(MergeDataKeywordYearCount,Rtitle %in% MergeDataKeywordYearCount$Rtitle)

#Reduced <- subset(Condensed, SummaryKeywords$weight>0.007)
MergeDataKeywordNarrowRangeGraph3$x <- as.numeric(MergeDataKeywordNarrowRangeGraph3$x)

# Create a list of techniques to include
Textiles.list <- paste(c("WOOL",
                         "ACRYLIC",
                         "VISCOSE",
                         "POLYESTER",
                         "COTTON",
                         "ACRYLIC ACID",
                         "SYNTHETIC FIBRE",
                         "NYLON",
                         "POLYMER",
                         "POLYAMIDE",
                         "TEXTILE",
                         "TEXTILE FIBRE",
                         "CLOTHING"), collapse = ';')
Textileslist <- as.data.frame(Textiles.list)

#Split Column "Textiles.list" in row by the separator ";", remove leading white space to generate list
Textileslist <- Textileslist %>% 
  mutate(Textiles.list = strsplit(as.character(Textiles.list), ";")) %>% 
  unnest(Textiles.list) %>%
  mutate_if(is.character, str_trim)

# Select from "ScopusKeywordNarrowRangeGraph3" every keywords from "Textiles.list" and place it in a new list "TechniqueList"
Textileslist <-subset(MergeDataKeywordNarrowRangeGraph3,Rtitle %in% Textileslist$Textiles.list)


#### plot second graph
# Create a new variable from incidence
Textileslist$Incidenceweight <- cut(Textileslist$x,
                                    breaks = c(-1,0,1,2,max(Textileslist$x,na.rm=T)),
                                    labels=c("0","1","2","3-5"))

GraphTemp1Ter <- Textileslist %>%
  # convert state to factor and reverse order of levels
  mutate(KeywordsCorrected=factor(Rtitle,levels=rev(sort(unique(Rtitle))))) %>%
  # create a new variable from count
  mutate(countfactor=cut(x,breaks=c(-1,0,1,2,max(x,na.rm=T)),
                         labels=c("0","1","2","3-5")))  %>%
  # change level order
  mutate(countfactor=factor(as.character(countfactor),levels=rev(levels(countfactor))))
# InterpolKeywordList$WYear <- gsr(InterpolKeywordList$Year,year$Var1,1/year$Freq)
GraphTemp2 <- aggregate(GraphTemp1Ter[, 1], list(GraphTemp1Ter$KeywordsCorrected), min)

GraphTemp1Ter$graphorder <- as.numeric(gsr(GraphTemp1Ter$KeywordsCorrected,GraphTemp2$Group.1,GraphTemp2$x))

# assign text colour
textcol <- "black"

# further modified ggplot
p2 <- ggplot(GraphTemp1Ter,aes(x=Year,y=reorder(KeywordsCorrected,graphorder),fill=countfactor))+
  geom_tile(colour="white",size=0.2)+
  guides(fill=guide_legend(title="Count"))+
  #  labs(x="",y="",title="Keywords found in gunshot residue publication")+
  labs(x="Year",y="",title="")+
  scale_y_discrete(expand=c(0,0))+
  scale_x_continuous(breaks=c(1965,1975,1985,1995,2005,2015))+
  scale_fill_manual(values=c("#000099","#3366ff","#99ccff"),na.value = "grey90")+
  coord_fixed()+
  theme_grey(base_size=8)+
  theme(legend.position="right",legend.direction="vertical",
        legend.title=element_text(colour=textcol),
        legend.margin=margin(grid::unit(0,"cm")),
        legend.text=element_text(colour=textcol,size=7),
        legend.key.height=grid::unit(0.8,"cm"),
        legend.key.width=grid::unit(0.2,"cm"),
        axis.text.x=element_text(size=8,colour=textcol),
        axis.text.y=element_text(vjust=0.2,colour=textcol),
        axis.ticks=element_line(size=0.4),
        plot.background=element_blank(),  # element_rect(fill, colour, size, linetype, color))
        panel.border=element_blank(),
        plot.margin=margin(0.7,0.4,0.1,0.2,"cm"),
        plot.title=element_text(colour=textcol,hjust=0,size=12))
show(p2)
ggplotly(p2)
ggsave("SopWoS_Textile Keyword Trend_04-06-20.png", p2, width = 8, height = 3, units = "in", dpi=150, path = "Results")

#####______________2D matrix______________##########
# create a list with the keywords with a frequency >5
TopKeywords <- GraphTemp1 %>%
  select(Rtitle)

# Remove duplicates to create the list of the top keywords
TopKeywordsList <- TopKeywords %>% distinct()
names(TopKeywordsList) <- c("TopKeywords")

# Export to Excel to create the correlation Table
#write.table(TopKeywordsList, file = "TopKeywordsList_AKeywords.csv", quote = F, sep = ",", row.names = F)
#write.table(MergeDataKeywordListTemp2, file = "MergeKeywordListTemp2_Akeywords.csv", quote = F, sep = ";", row.names = F)

# Import correlation Table
MatrixKeyword <- read.csv("Matrix AKeywords sup5 - step2.txt", sep="\t", header=T, check.names=FALSE)

# transform the column with numbers into num. the number of row must be specified and adapt to the dataset
MatrixKeywordbis <- as.data.frame(sapply(MatrixKeyword[,2:67], function(x) as.numeric(x)))
Matrix <- cbind(Title=MatrixKeyword$Title, MatrixKeywordbis)
Matrixbis <- rowsum(Matrix[,2:67], Matrix$Title)

# remove from Matrixbis keywords that are not realeant 
# for Index+ authors keywords mixed
#MatrixFinal <- subset(Matrixbis, select=-c(ARTICLE, PRIORITY.JOURNAL, REVIEW, CONFERENCE.PAPER, HUMAN, FEMALE, MALE,ANIMAL, NONHUMAN))
# for authors keywords only
MatrixFinal <- Matrixbis

# Create the matrix
Matriceplot <- cor(MatrixFinal, method = "spearman")

# Plot the matix
corrplot(Matriceplot, method = "color", type = "upper", tl.col = "black", tl.cex=0.5, col = brewer.pal(n = 11, name = "RdBu"))

####################### Plot the matrix with ggplot ##############################
# the matrix need to be melt first ( package reshape2 require)
melted_matrice <- melt(Matriceplot)
head(melted_matrice)

# Get only the upper triangle
get_upper_tri <- function(Matriceplot){
  Matriceplot[lower.tri(Matriceplot)]<- NA
  return(Matriceplot)
}
upper_tri <- get_upper_tri(Matriceplot)
upper_tri
# Get only the lower triangle
get_lower_tri<-function(Matriceplot){
  Matriceplot[lower.tri(Matriceplot)] <- NA
  return(Matriceplot)
}

lower_tri <- get_lower_tri(Matriceplot)
lower_tri

# choose upper or lower triangle there
melted_matrice <- melt(lower_tri, na.rm = TRUE)

ggplotmatrix <- ggplot(data = melted_matrice, aes(x= reorder(Var2, desc(Var2)), Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low="darkblue", mid = "white", high = "red", midpoint = 0, limit = c(-1,1), space = "Lab", name="Spearman\nCorrelation") +
  theme_classic()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1),
        axis.text.y = element_text(vjust = 1, size = 12, hjust = 1,))+
  labs(y="", x = "")
show(ggplotmatrix)
ggplotly(ggplotmatrix)

# to export the table
#write.table(melted_matrice, file = "Matrix_table sup5.csv", sep = ",", row.names = F)
